# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18 base image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy source code and other necessary files
COPY src ./src
COPY tsconfig.json ./
COPY .env ./

# Build the TypeScript files
RUN npm run build

# Use a smaller base image for the release
FROM node:18-slim AS release

# Set working directory
WORKDIR /app

# Copy the built files and necessary resources
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set environment variable for Node.js
ENV NODE_ENV=production

# Set the entrypoint
ENTRYPOINT ["node", "build/index.js"]
